token:
  expiration_time: 864000000 
  secret: '{cipher}AYANPtr30IK9nPXc/TQLltkwyj+R4/BMQexwT7FZU4fCzT6pX3HgNGBmw514dXtp0N2JyM/aYeDoVfzRnC6l4p0F8Ri+nZvdHjkNmIiQzZHGJ/4gmEXhLrmY7dFHjNnfJkJSu1Xkaaw/Lqilh4p2JWqwIeIqMx9Rx2eBDR6eyXdfNmLlV2/bnhWxmbUiNa9W7eSNe1tEg02vXVhc7iLOsTCq5r6KEZoXU0RNbUEKjQO4XTsGJQXsLlgufgzY9Lw76uWRxnfJFMuGT6SkRvHVkc9MP4KlW6Z0kn1BNz/LfJz9h/DlRWy0BaK35YQ6amIih8J5atSqHz7SmSGIaWRTMt344+7udRBmMTrDvvdVzPCrQ3GL6oa43kU+VojD+eZLQdie5vWzDCuv6jZQszH5ghxZ1c68AVAlKmMTnsWmJZJawpQllziYq+wnfRNtTvRwi2lmaMFp2o4TNFwJWUgKzK6WAz79CJuw3oRpZvOVeHWOxwEn9wz38RTRzvIEy8rH2gN+5TS4PsIpL8xdcmIzxiqxV/Els8J2QH6Y8BFgh4ibJ6YJ6/L+7haEOsH0+4QWLlh9GRDH9mjoAqrmxWgjLmhL/Vik6lkPudzha/i7OJcMdOZNJtUl9AqEysLMftTV38s='

gateway:
  ip: 172.18.0.1
