spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}AYB04knMHBW5ue/HTQL18XSN4z5mQ+zBgpeMzsbtB0Q8LixZftRl/2nz/Qa7P3FgLptZMLPs6Du9lBV4hFyQdy4qwQurlpWcTDYn4zNHLATk8f4UeCHDaUrjwKG7bIn+sonliIILRnz95K/ICPtNycnmp0ZGIqO5hP7SQpaUPDuueZUx+i2EB1kfdyx6nIoubvd7hdu8YpSIdL077EyeYrFvinv7DxnNcRHKdBGmmEsS3/czNyjNrF6y4Nc3uLw5jn9NLRjzP9xNWB3oknTYdUjD3Nxi/IBASVI9WKGgjWuQ18+4NP7onky1Tg0nESWjkcPOCTdUrVVKK2/E2pgU9HettD+jpDTuq1JPjIIRAEgjvrXzF1XDJHM4ynh7P93nijvaJXRxdcidl6IxGK0CKGw7NhtQOIhI8ZSrTbylKsoYdF2pdtqF6d2uo+fSX/r77A0eEuvafAdNejTUNPK3rEq+mbDWl7g9DeSZMfMOuYou86c48sAy03I7YOo6Nv64RrtrOHJC/e7o4LjFOHek0sIjakblHnT7JQ/0H2eqQSqcsw=='

app:
  payment:
    apiToken: '{cipher}AYBiqIwR47EUXVMiUUgQA3MY65xE1hPU53UhatBAH5eoDPTnWnUBggXrGYtBCgy2+wpCZieRQLYA1w+pA6U81RdD/FyEVKwxEoPfuwgQaaFNPBkbxKc1Ag1ot1jpGM+P5uiROQ5bSd40Dh6Yzf+crbZwpe4szLddmJ7fs4NaHCT4OEsRrEpe2wPZwnGyTQQyH05N4O7WVhNFnSqS8IWHnmRjkKTgMW8gFYt1f1pZ8uUaFo71vjQ9zrcwjtIGJuXepq2001XW3/y+oKkXLmoHlbWlUxS9auuRI7QpZIqBjrIqjQ74pdHsyVwIyl6I690UleggooE8WmSs/EFQipsLOLJG8ShLisuKnZcG4xn+cw2OTt8YNCZpH2HojSCVP5RmsFnrvoli3IbdLNme8dD95yg7jQZvGZLyZGtA4HNdqerXCtDSleFcxvzCu3LW1AOv0lhfxMT70qBXlMjX2bHtnmCJ/ZABESX6nXoUB3GFSmWHvmEr0pixEQMOmIb77p6i0t6NOSgz2Qt7RjxnhgMlbUBsp9l83cHeDt4E1BDkHp8VccghjEfAI0jVoSPULOQdOVs='

logging:
  level:
    root: INFO
